// app/layout.tsx
import Header from "./_components/header";

export const metadata = {
    title: "My App", // ページのタイトルを設定
    description: "Generated by Next.js", // ページの説明
  };
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <html lang="en">
        <body>
        <Header />
          {children}
        </body>
      </html>
    );
  }
  